#!/usr/bin/env python2
# -*- coding: utf-8 -*-

# Given any initial natural number, consider the sequence
# of numbers generated by repeatedly following the rule:
#
# divide by two if the number is even or
# multiply by 3 and add 1 if the number is odd.
#
# The Collatz conjecture states that this sequence always
# terminates at 1.

try:
    import simplegui
except ImportError:
    import SimpleGUICS2Pygame.simpleguics2pygame as simplegui


def init(start):
    """Initializes n."""
    global res, maxnum
    res = start
    maxnum = start
    print "Input is", res


def get_next(current):
    if current % 2 == 0:
        return current // 2
    else:
        return current * 3 + 1


def update():
    global res, maxnum
    if res == 1:
        timer.stop()
        print "Output is", maxnum
    else:
        res = get_next(res)
        if res > maxnum:
            maxnum = res


timer = simplegui.create_timer(1, update)

# init(23)
init(217)
timer.start()
